sw-6545 adding priority for managers #minor
ministryofjustice/opg-sirius-supervision-workflow pull request #330
Opened 2023-05-23 13:06 UTC by Nicholassully

2023-05-26 07:30 UTC, denialanderror requested changes

2023-05-26 08:37 UTC, Nicholassully commented on json-server/config/success-rerouter.js
> +            req.url = `/successes-${successRoute}`;
I changed it as Go was complaining about the Id being a string and not being able to unmarshal it to a int. Thats way I changed it

2023-05-26 08:37 UTC, Nicholassully commented on web/template/layout/table.gotmpl
> +            {{ end }}
I am unsure how to do that in class but happy to talk about it.

2023-05-26 08:37 UTC, Nicholassully commented on internal/server/workflow.go
> +	errorCheck := len(vars.Errors) == 0
done

2023-05-26 08:48 UTC, denialanderror commented on web/template/layout/table.gotmpl
> +            {{ end }}
Sorry, Github's formatting broke and ignored the code I wrote. See updated comment.

2023-05-26 08:49 UTC, denialanderror commented on json-server/config/success-rerouter.js
> +            req.url = `/successes-${successRoute}`;
Go shouldn't care and the last part of a URL doesn't have to be an ID of any sort. This works fine in the Hubs so I'd suggest checking how it works there if it's not working here. Let me know if you need a hand.

2023-05-26 08:57 UTC, Nicholassully commented on web/template/layout/table.gotmpl
> +            {{ end }}
ah cool thank you

2023-05-26 08:59 UTC, Nicholassully commented on json-server/config/success-rerouter.js
> +            req.url = `/successes-${successRoute}`;
I think that we will need a chat than as I really tried many different ways :/

2023-05-26 13:30 UTC, Nicholassully commented on internal/server/workflow.go
> +				return errors.New("Only managers can set priority on tasks")
done

2023-06-01 10:28 UTC, denialanderror approved these changes

2023-06-01 14:34 UTC, merged